= /# INTERFACES //
=   /<lover>/
=     <>[{lover:name}@2;^<>[+{lover:name}@2;][{lover:name}@2;<>
=     <>[+{lover:name}@2;]<>
=       <->#{lover:name}@2;>@4;A<->a#{lover:name}@2;><->
=       <->#{lover:name}@2;>@4;B<->b#{lover:name}@2;><->
=       <->#{lover:name}@2;>@4;C<->c#{lover:name}@2;><->
=       <>
=     <>[{lover:name}@2;]<>
=       <->#{lover:name}@2;>@3;<-><->
=       <>
=     /

= /# FUNCTIONS //
=   /[lover^/[+lover][lover/
=   /[+lover]/
=     []#lover>@2;A[]a#lover>[]
=     []#lover>@2;B[]b#lover>[]
=     []#lover>@2;C[]c#lover>[]
=     /
=   /[lover]/
=     []#lover>@2;[][]
=     /