= /# INTERFACES //
=   /<reverse>/
=     <>[{reverse:name}@2;^<>[+{reverse:name}@2;][{reverse:name}@2;<>
=     <>#{reverse:name}@2;^<>#{reverse:name}@2;>#{reverse:name}@2;<>
=     <>[+{reverse:name}@2;]<>
=       <->#{reverse:name}@2;>@4;A<{reverse:name}@2;#<-><{reverse:name}@2;#A<->
=       <->#{reverse:name}@2;>@4;B<{reverse:name}@2;#<-><{reverse:name}@2;#B<->
=       <->#{reverse:name}@2;>@4;C<{reverse:name}@2;#<-><{reverse:name}@2;#C<->
= 
=       <->#{reverse:name}@2;>@4;AA<->A#{reverse:name}@2;>A<->
=       <->#{reverse:name}@2;>@4;AB<->B#{reverse:name}@2;>A<->
=       <->#{reverse:name}@2;>@4;AC<->C#{reverse:name}@2;>A<->
= 
=       <->#{reverse:name}@2;>@4;BA<->A#{reverse:name}@2;>B<->
=       <->#{reverse:name}@2;>@4;BB<->B#{reverse:name}@2;>B<->
=       <->#{reverse:name}@2;>@4;BC<->C#{reverse:name}@2;>B<->
= 
=       <->#{reverse:name}@2;>@4;CA<->A#{reverse:name}@2;>C<->
=       <->#{reverse:name}@2;>@4;CB<->B#{reverse:name}@2;>C<->
=       <->#{reverse:name}@2;>@4;CC<->C#{reverse:name}@2;>C<->
=       <>
=     <>[{reverse:name}@2;]<>
=       <->#{reverse:name}@2;>@4;<{reverse:name}@2;#<-><{reverse:name}@2;#<->
=       <-><{reverse:name}@2;#@4;<-><->
=       <>
=   /

= /# FUNCTIONS //
=   /[reverse^/[+reverse][reverse/
=   /#reverse^/#reverse>#reverse/
=   /[+reverse]/
=     []#reverse>@2;A<reverse#[]<reverse#A[]
=     []#reverse>@2;B<reverse#[]<reverse#B[]
=     []#reverse>@2;C<reverse#[]<reverse#C[]
= 
=     []#reverse>@2;AA[]A#reverse>A[]
=     []#reverse>@2;AB[]B#reverse>A[]
=     []#reverse>@2;AC[]C#reverse>A[]
= 
=     []#reverse>@2;BA[]A#reverse>B[]
=     []#reverse>@2;BB[]B#reverse>B[]
=     []#reverse>@2;BC[]C#reverse>B[]
= 
=     []#reverse>@2;CA[]A#reverse>C[]
=     []#reverse>@2;CB[]B#reverse>C[]
=     []#reverse>@2;CC[]C#reverse>C[]
=     /
=   /[reverse]/
=     []#reverse>@2;<reverse#[]<reverse#[]
=     []<reverse#@2;[][]
=     /

