= /# INTERFACES //
=   /<sort>/
=     <>[{sort:name}@2;^<>[+{sort:name}@2;][{sort:name}@2;<>
=     <>#{sort:name}@2;^<>#{sort:name}@2;>#{sort:name}@2;<>
=     <>[+{sort:name}@2;]<>
=       <->#{sort:name}@2;>@4;AA<->A#{sort:name}@2;>A<->
=       <->#{sort:name}@2;>@4;AB<->A#{sort:name}@2;>B<->
=       <->#{sort:name}@2;>@4;AC<->A#{sort:name}@2;>C<->
= 
=       <->#{sort:name}@2;>@4;BA<->A#{sort:name}@2;>B<->
=       <->#{sort:name}@2;>@4;BB<->B#{sort:name}@2;>B<->
=       <->#{sort:name}@2;>@4;BC<->B#{sort:name}@2;>C<->
= 
=       <->#{sort:name}@2;>@4;CA<->A#{sort:name}@2;>C<->
=       <->#{sort:name}@2;>@4;CB<->B#{sort:name}@2;>C<->
=       <->#{sort:name}@2;>@4;CC<->C#{sort:name}@2;>C<->
=       <>
=     <>[{sort:name}@2;]<>
=       <->#{sort:name}@2;>@4;<-><->
=       <>
=   /

= /# FUNCTIONS //
=   /[sort^/[+sort][sort/
=   /#sort^/#sort>#sort/
=   /[+sort]/
=     []#sort>@1;AA[]A#sort>A[]
=     []#sort>@1;AB[]A#sort>B[]
=     []#sort>@1;AC[]A#sort>C[]
= 
=     []#sort>@1;BA[]A#sort>B[]
=     []#sort>@1;BB[]B#sort>B[]
=     []#sort>@1;BC[]B#sort>C[]
= 
=     []#sort>@1;CA[]A#sort>C[]
=     []#sort>@1;CB[]B#sort>C[]
=     []#sort>@1;CC[]C#sort>C[]
=     /
=   /[sort]/
=     []#sort>@1[][]
=     /