= /# INTERFACES //
=   /<upper>/
=     <>[{upper:name}@2;^<>[+{upper:name}@2;][{upper:name}@2;<>
=     <>[+{upper:name}@2;]<>
=       <->#{upper:name}@2;>@4;a<->A#{upper:name}@2;><->
=       <->#{upper:name}@2;>@4;b<->B#{upper:name}@2;><->
=       <->#{upper:name}@2;>@4;c<->C#{upper:name}@2;><->
=       <>
=     <>[{upper:name}@2;]<>
=       <->#{upper:name}@2;>@3;<-><->
=       <>
=     /

= /# FUNCTIONS //
=   /[upper^/[+upper][upper/
=   /[+upper]/
=     []#upper>@2;a[]A#upper>[]
=     []#upper>@2;b[]B#upper>[]
=     []#upper>@2;c[]C#upper>[]
=     /
=   /[upper]/
=     []#upper>@2;[][]
=     /