# File: Makefile

# make
all: main.cpp
	g++ -c main.cpp
	g++ main.o -o sfml-app -lsfml-audio -lsfml-network -lsfml-graphics -lsfml-window -lsfml-system
	./sfml-app


# Константы
TARGET = my_app
CC = gcc

PREF_SRC = ./src/
PERF_OBJ = ./obj/

# Все файлы вида
SRC = $(wildcard $(PREF_SRC)*.c)
# SRC = $(shell find . -name "*.c")
# Получить названия файлов из названий других
OBJ = $(patsubst $(PREF_SRC)%.c, $(PREF_OBJ)%.o, $(SRC))

# make
$(TARGET): $(OBJ)
	$(CC) $(OBJ) -o $(TARGET)

# Преобразование по фильтру, $< = правая часть, $@ = левая
$(PREF_OBJ)%.o : $(PREF_SRC)%.c
	$(CC) -c $< -o $@

# make clean
clean:
	rm $(TARGET) $(PREF_OBJ)*.o