/
= //
= / -> //
= 
= /[]/\\ -> \//
= /<>/\\ -> \\ -> \\ -> \//
= /**/\\ -> \\ -> \\ -> \\/
= 
= /# CONSTANTS //
= /{input}/abccba/
=  -> /{C}/^^^^^^/
= 
= /# INTERFACES //
= 
= /# FUNCTIONS //
= /[letter^/[+letter][letter/
= /[+letter]/
=  -> []#letter>\\a[]{letter:a}#letter>[]
=  -> []#letter>\\b[]{letter:b}#letter>[]
=  -> []#letter>\\c[]{letter:c}#letter>[]
= /
= /[letter]/
=  -> []#letter>[][]
= /
= 
= /# APP //
= [letter{C}]
= #letter>{input}