$cert = @(Get-ChildItem 'cert:\currentuser\my')[0]
Copy-Item $args[0] ".\signed\$($args[0])"
Set-AuthenticodeSignature ".\signed\$($args[0])" $cert | Out-Null
powershell ".\signed\$($args[0])"

# SIG # Begin signature block
# MIIFcgYJKoZIhvcNAQcCoIIFYzCCBV8CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUGZYf9qWAjJ+DSyRHgnyOdoAe
# OLWgggMWMIIDEjCCAfqgAwIBAgIQMbtBqGA7dLJPW5BHIMAqUjANBgkqhkiG9w0B
# AQsFADARMQ8wDQYDVQQDDAZIX1JPT1QwHhcNMjIwNTEzMDMwOTE5WhcNMjMwNTEz
# MDMyNzQ5WjAQMQ4wDAYDVQQDDAVIX1NVQjCCASIwDQYJKoZIhvcNAQEBBQADggEP
# ADCCAQoCggEBAKclD0YF+w+rDag8+IQv82LOGRbdompNwIC4v/z8Tk2GHFEWiVO+
# E+K0QDwkARh6kzOi1vXO6Z1K7NgmD/VFc0myjY265u8KwasDvPtqGC105fuk/58A
# rsbl2uN8t9OzFPSTgAWZCm2Azlf7wGG4deaLE9uarAPHAER1Yxlm+lwb7OmIv+pQ
# v9d45pRh64++CXs/vrGYyX6Q7/7Iv6EIM1yHo4YRcO9w5XXDRZbOBlIS0S/bpsJF
# uiosobZHISS+rHreF4JowO/ozbU6UnLxcb+k0u7eiidLyuW0SzuilOQICmPBFB3j
# q9+oK5jaZb3e004rWMWhkdBoEOB9s+2SQU0CAwEAAaNnMGUwDgYDVR0PAQH/BAQD
# AgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMDMB8GA1UdIwQYMBaAFEU2T/2K4S3OH9IY
# BGgaH+14mS8iMB0GA1UdDgQWBBQ+s2frPbClrfgXUvBGcbpS3dtLQjANBgkqhkiG
# 9w0BAQsFAAOCAQEAPbcGFiMjpRVivGDfpuyGAqSBhi7yYC5WmSyXKZyJ4TVpkS21
# CXUi06GCa0BMobH7hjxLMqQZfKetcbjwxYaT2y8yjD5blBSCE7dzrMCPvpfq3/h+
# ApOdpXQ3ibtjwSrEv7IqCeKWu0afA8+BEFZ4LGBVV2qShtgA33jjX2b2GkA5sJ6T
# woq9Eli1XGV/paKeMjfa26Vn81ONua9GKqDKvT/qE/DkpS/yvW09HgEZntr7K29g
# ltdo4OTh84K4zlApT7hZiwa6259BRynIAPeFwnI5Omy7DnTdcc4XrQwO+iL/8IHv
# S4PXPju71RUTXXKK/Ldg3ubWKASRKLfaQjwUpDGCAcYwggHCAgEBMCUwETEPMA0G
# A1UEAwwGSF9ST09UAhAxu0GoYDt0sk9bkEcgwCpSMAkGBSsOAwIaBQCgeDAYBgor
# BgEEAYI3AgEMMQowCKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEE
# MBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMCMGCSqGSIb3DQEJBDEWBBTE
# gWYQ43dgRC1CLxksQ352ffRmsjANBgkqhkiG9w0BAQEFAASCAQAUOGHBnl5AWlqw
# 9uCHUxPCpCk0ZWtVC0ENMrHpHzkqYhfMK3LO+T+oqF5Mlr/Duo4jHEN0cF3kvtU3
# +FA+gvzGqYcAl1cbVZjP1yjKLW8LYoMJFaQWTVCzPZf+RSdJYU1Xy2YLg/u+Nn3k
# Uq/zrMz5t038vYAH4p5pAH9VLki6lb9VDKj5PFwVsit6x+RkEZVioXDwSVHe3prG
# SQL7HyfaU8rzncPGMFchHiEjO/xrTEAP2As4sSjxiG2ejkHUYwfyrsJxVNALi7s1
# 219naOfEV97bK2qrCxrwYjlNbAkTOOmwuUUzkXrbj6liIqKKatMkJADbzqeM8kF0
# XnYnQMqi
# SIG # End signature block
