/=  /= //
= //
= / -> //
= 
= /<->/
=   \\ -> \\ -> \\ -> \\ -> \\ -> \\ -> \\ -> \/
=   /
= /<>/<->/
= /[]/<>/
= 
= 
= /# SYSTEM //
=   /[print] //
=   /[log] /[LOG]: /
=   /[br]/
/
= 
=   /}@2;/\\ -> \\ -> \\ -> \\ -> }/
=   /}@1;/}@2;/
=   /}@0;/}@1;/
= 
=   />@2;/\\ -> \\ -> \\ -> \\ -> >/
=   />@1;/>@2;/
=   />@0;/>@0;/
= 
=   /#@2;/\\ -> \\ -> \\ -> \\ -> #/
=   /#@1;/#@2;/
= 
=   /e@2;/\\ -> \\ -> \\ -> \\ -> e/
=   /e@1;/e@2;/
=   /e@0;/e@1;/
= 
= 
=   /{1}/^/
=   /{2}/{1}^/
=   /{3}/{2}^/
=   /{4}/{3}^/
=   /{5}/{4}^/
=   /{6}/{5}^/
=   /{7}/{6}^/
=   /{8}/{7}^/
=   /{9}/{8}^/
=   /{X}/{9}^/
= 
= /# CONSTANTS //
=   /{len}/{X}{X}{X}{X}/
= 
=   /{first}/abccbabba/
=   /{text}/lol pin !code hello world/
= 
= 
= /# INTERFACES //
=   /<set_code>/
=     [log] code has set[br]
=     <>!code@2;<>436782648721<>
=     /
= 
=   /<fix>/
=     [log] fixed "{fix:fixed}@1;"[br]
=     <>{fix:fixed}@1;<>*fixed*<>
=     /
= 
=   /<unfix>/
=     <>*fixed*<>{unfix:fixed}<>
=     /
= 
=   /<replace>/
=     <>{replace:from}@1;<>
=       {replace:to}@1;
=       <>
=     /
= 
=   /<rm>/
=     <>[{rm:a}@1;]<>
=       <->#{rm:a}@1;>@2;<-><->
=     <>
=     /
= 
= /# FUNCTIONS //
=   /[upper^/[+upper][upper/
=   /[+upper]/
=     []#upper>@1;a[]A#upper>[]
=     []#upper>@1;b[]B#upper>[]
=     []#upper>@1;c[]C#upper>[]
=     /
=   /[rm:upper]/<rm>/
=       /{rm:a}@0;/upper/
=   [rm:upper]
= 
=   /[lover^/[+lover][lover/
=   /[+lover]/
=     []#lover>@1;A[]a#lover>[]
=     []#lover>@1;B[]b#lover>[]
=     []#lover>@1;C[]c#lover>[]
=     /
=   /[rm:lover]/<rm>/
=       /{rm:a}@0;/lover/
=   [rm:lover]
= 
=   /[sort^/[+sort][sort/
=   /#sort^/#sort>#sort/
=   /[+sort]/
=     []#sort>@1;AA[]A#sort>A[]
=     []#sort>@1;AB[]A#sort>B[]
=     []#sort>@1;AC[]A#sort>C[]
= 
=     []#sort>@1;BA[]A#sort>B[]
=     []#sort>@1;BB[]B#sort>B[]
=     []#sort>@1;BC[]B#sort>C[]
= 
=     []#sort>@1;CA[]A#sort>C[]
=     []#sort>@1;CB[]B#sort>C[]
=     []#sort>@1;CC[]C#sort>C[]
=     /
=   /[rm:sort]/<rm>/
=       /{rm:a}@0;/sort/
=   [rm:sort]
= 
=   /[reverse^/[+reverse][reverse/
=   /#reverse^/#reverse>#reverse/
=   /[+reverse]/
=     []#reverse>@1;A<reverse#[]<reverse#A[]
=     []#reverse>@1;B<reverse#[]<reverse#B[]
=     []#reverse>@1;C<reverse#[]<reverse#C[]
= 
=     []#reverse>@1;AA[]A#reverse>A[]
=     []#reverse>@1;AB[]B#reverse>A[]
=     []#reverse>@1;AC[]C#reverse>A[]
= 
=     []#reverse>@1;BA[]A#reverse>B[]
=     []#reverse>@1;BB[]B#reverse>B[]
=     []#reverse>@1;BC[]C#reverse>B[]
= 
=     []#reverse>@1;CA[]A#reverse>C[]
=     []#reverse>@1;CB[]B#reverse>C[]
=     []#reverse>@1;CC[]C#reverse>C[]
=     /
=   /[reverse]/
=     []#reverse>@1;<reverse#[]<reverse#[]
=     []<reverse#@1;[][]
=     /
= 
=   /# Реализация интерфейса //
=   /[fix:1]/<fix>/
=           /{fix:fixed}@0;/hello/
=   /[fix:2]/<fix>/
=           /{fix:fixed}@0;/world/
= 
=   /[unfix:1]/<unfix>/
=             /{unfix:fixed}@0;/keks/
= 
=   /[replace:1]/<replace>/
=               /{replace:from}@0;/lol/
=               /{replace:to}@0;/kek/
=   
=   /# Анонимная функция и спуск интерфейса //
=   /[init]/
=     []{test:val}@0;[]!code[]
=     <set_code>
=     /
=     /{test:val}@0;/pin/
= 
= /# APP //
=   [fix:1]
=   [fix:2]
=   [unfix:1]
=   [replace:1]
=   [init]
= 
=   [upper{4}]
=   [sort{9}]
=   /{result}/#sort{9}>#upper>{first}/
= 
=   [reverse{9}]
=   [lover{4}]
=   /{reversed}/#lover>#reverse{9}>#upper>{first}<reverse#/
= 
=   [print] Upper result: {result}[br]
=   [print] Reversed result: {reversed}[br]
=   [print] Other text: {text}