/=  /= //
= //
= / -> //
= 
= /[]/
=   \\ -> \/
=   /
= /<>/
=   \\ -> \\ -> \\ -> \/
=   /
= 
= /}[VAR-0]/\\ -> }/
= /}[VAR-1]/.~ -> }/
= />[ARR-1]/.~ -> >/
= 
= /l[L-2]/.~.~l/
= 
= /.~/
=   \\ -> \\
=   /
= 
= 
= /[print]//
= 
= /# CONSTANTS //
=   /{input}/abccba lol pin !tpl hello world/
=       /{C}/^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^/
= 
=   /{1}/^/
=   /{2}/^^/
=   /{3}/^^^/
=   /{4}/^^^^/
=   /{5}/^^^^^/
=   /{6}/^^^^^^/
=   /{7}/^^^^^^^/
=   /{8}/^^^^^^^^/
=   /{9}/^^^^^^^^^/
= 
= /# INTERFACES //
=   /<code_tpl>/
=     <>!tpl[L-2]<>436782648721<>
=     /
= 
=   /<fix>/
=     <>{fix:a}[VAR-1]<>*fixed*<>
=     /
= 
=   /<repl>/
=     <>{repl:a}[VAR-1]<>{repl:b}[VAR-1]<>
=     /
= 
= /# FUNCTIONS //
= /# Объявление счётчика //
= /# Использование указателей //
=   /[upper^/[+upper][upper/
=   /[+upper]/
=     []#upper>[ARR-1]a[]A#upper>[]
=     []#upper>[ARR-1]b[]B#upper>[]
=     []#upper>[ARR-1]c[]C#upper>[]
=     /
= 
= /# Удаление указателя //
=   /[upper]/
=     []#upper>[ARR-1][][]
=     /
= 
= /# Реализация интерфейса //
=   /[fix:hello]/<fix>/
=               /{fix:a}[VAR-0]/hello/
=   /[fix:world]/<fix>/
=               /{fix:a}[VAR-0]/world/
= 
=   /[repl:i]/<repl>/
=            /{repl:a}[VAR-0]/lol/
=            /{repl:b}[VAR-0]/kek/
=   
= /# Анонимная функция и спуск интерфейса //
=   /[test]/
=     []{test:val}[VAR-0][]!tpl[]
=     <code_tpl>
=     /
=          /{test:val}[VAR-0]/pin/
= 
= /# APP //
=   [fix:hello]
=   [fix:world]
=   [repl:i]
=   [test]
= 
=   [upper{3}]
= 
=   /{result}/#upper>{input}/
= 
= 
=   [print] -> {result}