/=  /= //
= //
= / -> //
= 
= /[]/
=   \\ -> \/
=   /
= /<>/
=   \\ -> \\ -> \\ -> \/
=   /
= 
= /}[VAR-0]/\\}/
= 
= /}[VAR-1]/.~}/
= />[ARR-1]/.~>/
= /a[A-1]/.~a/
= /b[B-1]/.~b/
= /c[C-1]/.~c/
= 
= /l[L-2]/.~.~l/
= 
= /.~/
=   \\ -> \\
= /
= 
= 
= /[print]//
= 
= /# CONSTANTS //
=   /{input}/abccba my just_tpl hello world/
=       /{C}/^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^/
= 
=     /{1}/^/
=     /{2}/^^/
=     /{3}/^^^/
=     /{4}/^^^^/
=     /{5}/^^^^^/
=     /{6}/^^^^^^/
=     /{7}/^^^^^^^/
=     /{8}/^^^^^^^^/
=     /{9}/^^^^^^^^^/
= 
= /# INTERFACES //
=   /<just_tpl>/
=     <>just_tpl[L-2]<>"code: 1234"<>
=     /
= 
=   /<i>/
=     <>{i:a}[VAR-1]<>i_fix<>
=     /
= 
=   /<repl>/
=     <>{repl:a}[VAR-1]<>{repl:b}[VAR-1]<>
=     /
= 
= /# FUNCTIONS //
= /# Объявление счётчика //
=   /[sort^/[+sort][sort/
=   /[+sort]/
=     []ba[A-1][]ab[]
=     []cb[B-1][]bc[]
=     []ca[A-1][]ac[]
=     /
= 
= /# Использование указателей //
=   /[upper^/[+upper][upper/
=   /[+upper]/
=     []#upper>[ARR-1]a[]A#upper>[]
=     []#upper>[ARR-1]b[]B#upper>[]
=     []#upper>[ARR-1]c[]C#upper>[]
=     /
= 
= /# Удаление указателя //
=   /[upper]/
=     []#upper>[ARR-1][][]
=     /
= 
= /# Реализация интерфейса //
=   /[i:hello]/<i>/
=             /{i:a}[VAR-0]/hello/
=   /[i:world]/<i>/
=             /{i:a}[VAR-0]/world/
=   
= /# Анонимная функция и спуск интерфейса //
=   /[test]/
=     []{test:val}[VAR-0][]test[]
=     <just_tpl>
=     /
=       /{test:val}[VAR-0]/my/
= 
= /# APP //
=   [i:hello]
=   [i:world]
=   [test]
= 
=   [upper{2}]
= 
=   /{result}/#upper>{input}/
= 
= 
=   [print] -> {result}