/=  /= //
= //
= / -> //
= 
= /<->/
=   \\ -> \\ -> \\ -> \\ -> \\ -> \\ -> \\ -> \/
=   /
= /<>/<->/
= /[]/<>/
= 
= 
= /# SYSTEM //
=   /[print] //
=   /[log] /[LOG]: /
=   /[br]/
/
= 
=   /@----;/
=     \\ -> \\ -> \\ -> \\
=     \\ -> \\ -> \\ -> \\
=     \\ -> \\ -> \\ -> \\
=     \\ -> \\ -> \\ -> \\
=     /
=   /@---;/@----;/
= 
=   /# FOR POINTER //
=   />@4;/@----;>/
=   />@3;/>@4;/
=   />@2;/>@3;/
=   />@1;/>@2;/
= 
=   /# FOR STOP POINTER //
=   /#@4;/@----;#/
=   /#@3;/#@4;/
=   /#@2;/#@3;/
=   /#@1;/#@2;/
= 
=   /# FOR CONSTANTS //
=   /}@3;/@---;}/
=   /}@2;/}@3;/
=   /}@1;/}@2;/
= 
= 
=   /{1}/^/
=   /{2}/{1}^/
=   /{3}/{2}^/
=   /{4}/{3}^/
=   /{5}/{4}^/
=   /{6}/{5}^/
=   /{7}/{6}^/
=   /{8}/{7}^/
=   /{9}/{8}^/
=   /{X}/{9}^/
= 
= /# CONSTANTS //
=   /{len}/{X}{X}{X}{X}/
=   /{text}/abccbabba/
= 
= /# RANK 4 //
= 
= /# RANK 3 //
=   /<upper>/
=     <>[<+upper:n>^<>[+<+upper:n>][<+upper:n><>
=     <>[+<+upper:n>]<>
=       <-><+upper:r>a<->A<+upper:r><->
=       <-><+upper:r>b<->B<+upper:r><->
=       <-><+upper:r>c<->C<+upper:r><->
=       <-><+upper:r>d<->D<+upper:r><->
=       <>
=     <>[<+upper:n>]<>
=       <-><+upper:r><-><->
=       <>
=     /
=     /<+upper:r>/#<+upper:n>>@4;/
=     /<+upper:n>/{upper:name}@2;/
= 
= 
=   /<lover>/
=     <>[<+lover:n>^<>[+<+lover:n>][<+lover:n><>
=     <>[+<+lover:n>]<>
=       <-><+lover:r>A<->a<+lover:r><->
=       <-><+lover:r>B<->b<+lover:r><->
=       <-><+lover:r>C<->c<+lover:r><->
=       <-><+lover:r>D<->d<+lover:r><->
=       <>
=     <>[<+lover:n>]<>
=       <-><+lover:r><-><->
=       <>
=     /
=     /<+lover:r>/#<+lover:n>>@4;/
=     /<+lover:n>/{lover:name}@2;/
= 
= 
=   /<reverse>/
=     <>[<+reverse:n>^<>[+<+reverse:n>][<+reverse:n><>
=     <>#<+reverse:n>^<>#<+reverse:n>>#<+reverse:n><>
=     <>[+<+reverse:n>]<>
=       <-><+reverse:r>A<+reverse:l><-><+reverse:l>A<->
=       <-><+reverse:r>B<+reverse:l><-><+reverse:l>B<->
=       <-><+reverse:r>C<+reverse:l><-><+reverse:l>C<->
= 
=       <-><+reverse:r>AA<->A<+reverse:r>A<->
=       <-><+reverse:r>AB<->B<+reverse:r>A<->
=       <-><+reverse:r>AC<->C<+reverse:r>A<->
= 
=       <-><+reverse:r>BA<->A<+reverse:r>B<->
=       <-><+reverse:r>BB<->B<+reverse:r>B<->
=       <-><+reverse:r>BC<->C<+reverse:r>B<->
= 
=       <-><+reverse:r>CA<->A<+reverse:r>C<->
=       <-><+reverse:r>CB<->B<+reverse:r>C<->
=       <-><+reverse:r>CC<->C<+reverse:r>C<->
=       <>
=     <>[<+reverse:n>]<>
=       <-><+reverse:r><+reverse:l><-><+reverse:l><->
=       <-><+reverse:l><-><->
=       <>
=     /
=     /<+reverse:r>/#<+reverse:n>>@4;/
=     /<+reverse:l>/<<+reverse:n>#/
=     /<+reverse:n>/{reverse:name}@2;/
= 
=   /<sort>/
=     <>[<+sort:n>^<>[+<+sort:n>][<+sort:n><>
=     <>#<+sort:n>^<>#<+sort:n>>#<+sort:n><>
=     <>[+<+sort:n>]<>
=       <-><+sort:r>AA<->A<+sort:r>A<->
=       <-><+sort:r>AB<->A<+sort:r>B<->
=       <-><+sort:r>AC<->A<+sort:r>C<->
= 
=       <-><+sort:r>BA<->A<+sort:r>B<->
=       <-><+sort:r>BB<->B<+sort:r>B<->
=       <-><+sort:r>BC<->B<+sort:r>C<->
= 
=       <-><+sort:r>CA<->A<+sort:r>C<->
=       <-><+sort:r>CB<->B<+sort:r>C<->
=       <-><+sort:r>CC<->C<+sort:r>C<->
=       <>
=     <>[<+sort:n>]<>
=       <-><+sort:r><-><->
=       <>
=     /
=     /<+sort:r>/#<+sort:n>>@4;/
=     /<+sort:n>/{sort:name}@2;/
= 
= /# RANK 2 //
=   /[init:fst]/<upper><sort>/
=     /{upper:name}@1;/fst:upper/
=      /{sort:name}@1;/fst:sort/
=     [init:fst]
= 
=   /[init:snd]/<upper><lover><reverse>/
=       /{upper:name}@1;/snd:upper/
=       /{lover:name}@1;/snd:lover/
=     /{reverse:name}@1;/snd:reverse/
=     [init:snd]
= 
= 
= /# RANK 1 //
=   [fst:upper{4}]
=   [fst:sort{9}]
= 
=   /{result}/
=     #fst:sort{9}>
=     #fst:upper>
=     {text}
=     /
= 
=   [snd:upper{4}]
=   [snd:reverse{9}]
=   [snd:lover{4}]
= 
=   /{reversed}/
=     #snd:lover>
=     #snd:reverse{9}>
=     #snd:upper>
=     {text}
=     <snd:reverse#
=     /
= 
= /# RANK 0 //
=   [print] Upper result:    {result}[br]
=   [print] Reversed result: {reversed}[br]