/=  /= //
= //
= / -> //
= 
= /@-----;/
=   \\ -> \\ -> \\ -> \\
=   \\ -> \\ -> \\ -> \\
=   \\ -> \\ -> \\ -> \\
=   \\ -> \\ -> \\ -> \\
=   \\ -> \\ -> \\ -> \\
=   \\ -> \\ -> \\ -> \\
=   \\ -> \\ -> \\ -> \\
=   \\ -> \\ -> \\ -> \\
=   /
= /@----;/@-----;/
= /@---;/@----;/
= /@--;/@---;/
= /@-;/@--;/
= 
= /[6]/
=   @-----; -> @----; -> @---; -> @--; -> @-; -> \/
=   /
= /[5]/[6]/
= /[4]/[5]/
= /[3]/[4]/
= /[2]/[3]/
= 
= 
= /# SYSTEM //
=   /[print] //
=   /[log] /[LOG]: /
=   /[br]/
/
= 
=   /# FOR POINTER //
=   />@4;/@----;>/
=   />@3;/>@4;/
=   />@2;/>@3;/
=   />@1;/>@2;/
= 
=   /# FOR STOP POINTER //
=   /#@4;/@----;#/
=   /#@3;/#@4;/
=   /#@2;/#@3;/
=   /#@1;/#@2;/
= 
=   /# FOR CONSTANTS //
=   /}@3;/@---;}/
=   /}@2;/}@3;/
=   /}@1;/}@2;/
= 
= 
=   /{1}/^/
=   /{2}/{1}^/
=   /{3}/{2}^/
=   /{4}/{3}^/
=   /{5}/{4}^/
=   /{6}/{5}^/
=   /{7}/{6}^/
=   /{8}/{7}^/
=   /{9}/{8}^/
=   /{X}/{9}^/
= 
= /# CONSTANTS //
=   /{len}/{X}{X}{X}{X}/
=   /{text}/abccbabba/
=   /{text2}/ababcdeffedcba/
= 
= /# RANK 4 //
=   /<reverse:tmp>/
=     [6]<+reverse:r>{reverse:tmp:n}@2;<+reverse:l>[6]<+reverse:l>{reverse:tmp:n}@2;[6]
=     [6]<+reverse:r>{reverse:tmp:n}@2;A[6]A<+reverse:r>{reverse:tmp:n}@2;[6]
=     [6]<+reverse:r>{reverse:tmp:n}@2;B[6]B<+reverse:r>{reverse:tmp:n}@2;[6]
=     [6]<+reverse:r>{reverse:tmp:n}@2;C[6]C<+reverse:r>{reverse:tmp:n}@2;[6]
=     [6]<+reverse:r>{reverse:tmp:n}@2;D[6]D<+reverse:r>{reverse:tmp:n}@2;[6]
=     [6]<+reverse:r>{reverse:tmp:n}@2;E[6]E<+reverse:r>{reverse:tmp:n}@2;[6]
=     [6]<+reverse:r>{reverse:tmp:n}@2;F[6]F<+reverse:r>{reverse:tmp:n}@2;[6]
=     /
= 
= 
= /# RANK 3 //
=   /<reverse:tmp:A>/<reverse:tmp>//{reverse:tmp:n}@1;/A/
=   /<reverse:tmp:B>/<reverse:tmp>//{reverse:tmp:n}@1;/B/
=   /<reverse:tmp:C>/<reverse:tmp>//{reverse:tmp:n}@1;/C/
=   /<reverse:tmp:D>/<reverse:tmp>//{reverse:tmp:n}@1;/D/
=   /<reverse:tmp:E>/<reverse:tmp>//{reverse:tmp:n}@1;/E/
=   /<reverse:tmp:F>/<reverse:tmp>//{reverse:tmp:n}@1;/F/
= 
=   /<reverse>/
=     [3][<+reverse:n>^[3][+<+reverse:n>][<+reverse:n>[3]
=     [3]#<+reverse:n>^[3]#<+reverse:n>>#<+reverse:n>[3]
=     [3][+<+reverse:n>][3]
=       <reverse:tmp:A>
=       <reverse:tmp:B>
=       <reverse:tmp:C>
=       <reverse:tmp:D>
=       <reverse:tmp:E>
=       <reverse:tmp:F>
=       [3]
=     [3][<+reverse:n>][3]
=       [4]<+reverse:r><+reverse:l>[4]<+reverse:l>[4]
=       [4]<+reverse:l>[4][4]
=       [3]
=     /
=     /<+reverse:r>/#<+reverse:n>>@4;/
=     /<+reverse:l>/<<+reverse:n>#/
=     /<+reverse:n>/{reverse:name}@2;/
= 
= 
=   /<sort>/
=     [3][<+sort:n>^[3][+<+sort:n>][<+sort:n>[3]
=     [3]#<+sort:n>^[3]#<+sort:n>>#<+sort:n>[3]
=     [3][+<+sort:n>][3]
=       [4]<+sort:r>AA[4]A<+sort:r>A[4]
=       [4]<+sort:r>AB[4]A<+sort:r>B[4]
=       [4]<+sort:r>AC[4]A<+sort:r>C[4]
= 
=       [4]<+sort:r>BA[4]A<+sort:r>B[4]
=       [4]<+sort:r>BB[4]B<+sort:r>B[4]
=       [4]<+sort:r>BC[4]B<+sort:r>C[4]
= 
=       [4]<+sort:r>CA[4]A<+sort:r>C[4]
=       [4]<+sort:r>CB[4]B<+sort:r>C[4]
=       [4]<+sort:r>CC[4]C<+sort:r>C[4]
=       [3]
=     [3][<+sort:n>][3]
=       [4]<+sort:r>[4][4]
=       [3]
=     /
=     /<+sort:r>/#<+sort:n>>@4;/
=     /<+sort:n>/{sort:name}@2;/
= 
= 
=   /<upper>/
=     [3][<+upper:n>^[3][+<+upper:n>][<+upper:n>[3]
=     [3][+<+upper:n>][3]
=       [4]<+upper:r>a[4]A<+upper:r>[4]
=       [4]<+upper:r>b[4]B<+upper:r>[4]
=       [4]<+upper:r>c[4]C<+upper:r>[4]
=       [4]<+upper:r>d[4]D<+upper:r>[4]
=       [4]<+upper:r>e[4]E<+upper:r>[4]
=       [4]<+upper:r>f[4]F<+upper:r>[4]
=       [3]
=     [3][<+upper:n>][3]
=       [4]<+upper:r>[4][4]
=       [3]
=     /
=     /<+upper:r>/#<+upper:n>>@4;/
=     /<+upper:n>/{upper:name}@2;/
= 
= 
=   /<lover>/
=     [3][<+lover:n>^[3][+<+lover:n>][<+lover:n>[3]
=     [3][+<+lover:n>][3]
=       [4]<+lover:r>A[4]a<+lover:r>[4]
=       [4]<+lover:r>B[4]b<+lover:r>[4]
=       [4]<+lover:r>C[4]c<+lover:r>[4]
=       [4]<+lover:r>D[4]d<+lover:r>[4]
=       [4]<+lover:r>E[4]e<+lover:r>[4]
=       [4]<+lover:r>F[4]f<+lover:r>[4]
=       [3]
=     [3][<+lover:n>][3]
=       [4]<+lover:r>[4][4]
=       [3]
=     /
=     /<+lover:r>/#<+lover:n>>@4;/
=     /<+lover:n>/{lover:name}@2;/
= 
= 
= 
= /# RANK 2 //
=   /[init:fst]/<upper><sort>/
=     /{upper:name}@1;/fst:upper/
=     /{sort:name}@1;/fst:sort/
=     [init:fst]
= 
=   /[init:snd]/<upper><lover><reverse>/
=     /{upper:name}@1;/snd:upper/
=     /{lover:name}@1;/snd:lover/
=     /{reverse:name}@1;/snd:reverse/
=     [init:snd]
= 
= 
= /# RANK 1 //
=   [fst:upper{4}]
=   [fst:sort{9}]
= 
=   /{result}/
=     #fst:sort{9}>
=     #fst:upper>
=     {text}
=     /
= 
=   [snd:upper{X}{X}]
=   [snd:reverse{X}{X}]
=   [snd:lover{X}{X}]
= 
=   /{reversed}/
=     #snd:lover>
=     #snd:reverse{X}{X}>
=     #snd:upper>
=     {text2}
=     <snd:reverse#
=     /
= 
= /# RANK 0 //
=   [print] Upper result:    {result}[br]
=   [print] Reversed result: {reversed}[br]