/=  /= //
= //
= / -> //
= 
= /<->/
=   \\ -> \\ -> \\ -> \\ -> \\ -> \\ -> \\ -> \/
=   /
= /<>/<->/
= /[]/<>/
= 
= 
= /# SYSTEM //
=   /[print] //
=   /[log] /[LOG]: /
=   /[br]/
/
=   /@GET3;/
=     \\ -> \\ -> \\ -> \\
=     \\ -> \\ -> \\ -> \\
=     \\ -> \\ -> \\ -> \\
=     \\ -> \\ -> \\ -> \\
=     /
= 
=   /}@2;/\\ -> \\ -> \\ -> \\ -> }/
=   /}@1;/}@2;/
=   /}@0;/}@1;/
= 
=   />@3;/@GET3;>/
=   />@2;/>@3;/
=   />@1;/>@2;/
=   />@0;/>@1;/
= 
=   /#@2;/\\ -> \\ -> \\ -> \\ -> #/
=   /#@1;/#@2;/
=   /#@0;/#@1;/
= 
= 
=   /{1}/^/
=   /{2}/{1}^/
=   /{3}/{2}^/
=   /{4}/{3}^/
=   /{5}/{4}^/
=   /{6}/{5}^/
=   /{7}/{6}^/
=   /{8}/{7}^/
=   /{9}/{8}^/
=   /{X}/{9}^/
= 
= /# CONSTANTS //
=   /{len}/{X}{X}{X}{X}/
= 
=   /{text}/abccbabba/
= 
= 
= /# INTERFACES //
=   /<upper>/
=     <>[{upper:name}@1;^<>[+{upper:name}@1;][{upper:name}@1;<>
=     <>[+{upper:name}@1;]<>
=       <->#{upper:name}@1;>@3;a<->A#{upper:name}@1;><->
=       <->#{upper:name}@1;>@3;b<->B#{upper:name}@1;><->
=       <->#{upper:name}@1;>@3;c<->C#{upper:name}@1;><->
=       <>
=     <>[{upper:name}@1;]<>
=       <->#{upper:name}@1;>@2;<-><->
=       <>
=     /
= 
=   /<lover>/
=     <>[{lover:name}@1;^<>[+{lover:name}@1;][{lover:name}@1;<>
=     <>[+{lover:name}@1;]<>
=       <->#{lover:name}@1;>@3;A<->a#{lover:name}@1;><->
=       <->#{lover:name}@1;>@3;B<->b#{lover:name}@1;><->
=       <->#{lover:name}@1;>@3;C<->c#{lover:name}@1;><->
=       <>
=     <>[{lover:name}@1;]<>
=       <->#{lover:name}@1;>@2;<-><->
=       <>
=     /
= 
= /# FUNCTIONS //
=   /[upper:1]/<upper>/
=             /{upper:name}@0;/upper_first/
=             [upper:1]
= 
=   /[upper:2]/<upper>/
=             /{upper:name}@0;/upper_second/
=             [upper:2]
= 
=   /[lover:2]/<lover>/
=             /{lover:name}@0;/lover_first/
=             [lover:2]
= 
= 
=   /[sort^/[+sort][sort/
=   /#sort^/#sort>#sort/
=   /[+sort]/
=     []#sort>@1;AA[]A#sort>A[]
=     []#sort>@1;AB[]A#sort>B[]
=     []#sort>@1;AC[]A#sort>C[]
= 
=     []#sort>@1;BA[]A#sort>B[]
=     []#sort>@1;BB[]B#sort>B[]
=     []#sort>@1;BC[]B#sort>C[]
= 
=     []#sort>@1;CA[]A#sort>C[]
=     []#sort>@1;CB[]B#sort>C[]
=     []#sort>@1;CC[]C#sort>C[]
=     /
=   /[sort]/
=     []#sort>@1;[][]
=     /
= 
=   /[reverse^/[+reverse][reverse/
=   /#reverse^/#reverse>#reverse/
=   /[+reverse]/
=     []#reverse>@1;A<reverse#[]<reverse#A[]
=     []#reverse>@1;B<reverse#[]<reverse#B[]
=     []#reverse>@1;C<reverse#[]<reverse#C[]
= 
=     []#reverse>@1;AA[]A#reverse>A[]
=     []#reverse>@1;AB[]B#reverse>A[]
=     []#reverse>@1;AC[]C#reverse>A[]
= 
=     []#reverse>@1;BA[]A#reverse>B[]
=     []#reverse>@1;BB[]B#reverse>B[]
=     []#reverse>@1;BC[]C#reverse>B[]
= 
=     []#reverse>@1;CA[]A#reverse>C[]
=     []#reverse>@1;CB[]B#reverse>C[]
=     []#reverse>@1;CC[]C#reverse>C[]
=     /
=   /[reverse]/
=     []#reverse>@1;<reverse#[]<reverse#[]
=     []<reverse#@1;[][]
=     /
= 
= /# APP //
=   [upper_first{4}]
=   [sort{9}]
=   /{result}/#sort{9}>#upper_first>{text}/
= 
=   [upper_second{4}]
=   [reverse{9}]
=   [lover_first{4}]
=   /{reversed}/#lover_first>#reverse{9}>#upper_second>{text}<reverse#/
= 
=   [print] Upper result:    {result}[br]
=   [print] Reversed result: {reversed}[br]